version: '3.0'
services: 
  car-rental-service:
    image: car-rental-service
    build: 
      context: ./CarRentalService
      dockerfile: Dockerfile
    restart: on-failure
    hostname: carrentalservice
    container_name: er-telecom-car-rental-serv
    ports:
      - '8841:8080'
    environment: 
      SERVER_PORT: 8841
      POSTGRES_URL: jdbc:postgresql://postgresql:5432/crs
      POSTGRES_USER: crs
      POSTGRES_PASSWORD: crs
    depends_on: 
      - postgresql
  postgresql:
    image: postgres:latest
    restart: always
    container_name: er-telecom-postgres-db
    ports:
      - '5432:5432'
    environment: 
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./scripts/postgres-init.sql:/docker-entrypoint-initdb.d/001-postgres-init.sql