server:
  port: ${SERVER_PORT:8841}

spring:
  jpa:
    hibernate:
      ddl-auto: update
#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    placeholders:
#      schema: ${app.postgres.schema}

app:
  service-name: ${SERVICE_NAME:car-rental-service}
  postgres:
    driver-class-name: ${POSTGRES_DRIVER:org.postgresql.Driver}
    jdbc-url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/crs}
    username: ${POSTGRES_USER:crs}
    password: ${POSTGRES_PASSWORD:crs}
    schema: ${POSTGRES_DB:public}
    connection-timeout: 20000
    connection-init-sql: ALTER ROLE ${POSTGRES_USER:crs} SET search_path TO ${POSTGRES_DB:public}
    connection-test-query: SELECT 1
#  rest:
#    profile-service-url: ${PROFILE_SERVICE_URL:http://localhost:8941/api/v1/profileservice}
#    establishing-connection-timeout: 250
#    read-connection-timeout: 1750